name: survey-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - pip

  # Core dependencies from pyproject.toml
  - anndata>=0.11.0,<0.12.0
  - matplotlib>=3.10.0,<3.11.0
  - numpy>=2.0.0,<2.1.0
  - pandas>=2.2.0,<2.3.0
  - scanpy>=1.10.0,<1.11.0
  # - mudata>=0.3.2,<0.3.3 # need 0.3.1 has bug that preventing concat/merging, install from pip as of 28AUG25
  - scipy>=1.15.0,<1.16.0
  - seaborn>=0.13.0,<0.14.0
  - scikit-image>=0.25.0,<0.26.0
  - anytree>=2.12.0,<2.13.0

  # Additional dependencies for notebooks
  - harmonypy==0.0.10
  - python-igraph>=0.11.0,<0.12.0
  - ipykernel>=6.29.0,<6.30.0
  - ipywidgets>=8.1.0,<8.2.0
  - tqdm>=4.67.0,<4.68.0
  - ipympl>=0.9.0,<0.10.0
  - ipython>=8.35.0,<8.37.0

  - pip:
      - -e .
