name: survey-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - harmonypy==0.0.10
  - python-igraph>=0.11.0,<0.12.0
  - ipykernel>=6.29.0,<6.30.0
  - ipywidgets>=8.1.0,<8.2.0
  - tqdm>=4.67.0,<4.68.0
  - ipympl>=0.9.0,<0.10.0
  - pip:
      - -e .
