name: Python CI/CD

on:
  push:
    branches:
      - main
    # Add this 'paths' filter to control when the push workflow runs
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'environment.yml'
      - '.github/workflows/**' # Also good to run if you change the workflow itself

  pull_request:
    branches:
      - main
    # Also add the 'paths' filter here for pull requests
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'environment.yml'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest # It's good practice to use 'ubuntu-latest'

    strategy:
      matrix:
        # Use minor versions to always test against the latest patch release
        python-version: ["3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install with test dependencies
        pip install -e ".[test]"

    - name: Run pytest
      run: |
        pytest -v